# Generated by Django 5.1.6 on 2025-03-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_extractor', '0002_video_audio_extraction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.FilePathField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FilePathField(max_length=1000),
        ),
    ]
