# Generated by Django 5.1.6 on 2025-03-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_extractor', '0003_alter_audio_path_alter_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.FileField(max_length=1000, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='video',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio_extractor.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(max_length=1000, upload_to='videos/'),
        ),
    ]
